wandb_version: 1

exp_name:
  desc: null
  value: oodml_camelyon16
epochs:
  desc: null
  value: 200
lr:
  desc: null
  value: 0.0001
weight_decay:
  desc: null
  value: 1.0e-05
csv:
  desc: null
  value: ./camelyon16.csv
h5_path:
  desc: null
  value: ./patch_feats_pretrain_natural_supervised.h5
input_dim:
  desc: null
  value: 1024
n_classes:
  desc: null
  value: 2
K:
  desc: null
  value: 5
embed_dim:
  desc: null
  value: 512
tau:
  desc: null
  value: 1.0
lambda_plce:
  desc: null
  value: 0.5
ckpt_path:
  desc: null
  value: checkpoints/oodml_best_model.pt
_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1752488699.198219
    t:
      1:
      - 1
      - 5
      - 51
      - 53
      - 55
      2:
      - 1
      - 5
      - 51
      - 53
      - 55
      3:
      - 1
      - 13
      - 16
      - 23
      4: 3.10.12
      5: 0.15.8
      8:
      - 5
